---
abstract: 'Simplistic Object XML Mapper'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  Test::More: 0
  Test::UseAllModules: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-DOM
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  XML::LibXML: 1.63
  XML::LibXML::XPathContext: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00002
